version: '3.1'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "${CACHE_PORT}:6379"
    networks:
      - backend
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: local
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "${DB_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  backend:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  postgres:
